v1 of html project
mayanktyagi45/HTML-Training pull request #1
Opened 2023-07-19 04:48 UTC by mayanktyagi45

This is v1 of the html project

2023-07-19 05:17 UTC, PurnimaCompro requested changes

2023-07-19 05:17 UTC, PurnimaCompro commented on embedded.html
> +                    <source src="./assets/pexels_videos_2231485 (2160p).mp4" type="video/mp4">
indententation should be with 2 spaces

2023-07-19 05:17 UTC, PurnimaCompro commented on embedded.html
> +</html>
Remove Git error

2023-07-19 05:17 UTC, PurnimaCompro commented on index.html
> +    <iframe
Remove extra line spaces

2023-07-19 05:17 UTC, PurnimaCompro commented on styles/embedded.css
> +}
2 spaces

2023-07-19 05:17 UTC, PurnimaCompro commented on styles/embedded.css
> +}
Apply css on classes instead of selector

2023-07-19 05:27 UTC, mayanktyagi45 commented on embedded.html
> +                    <source src="./assets/pexels_videos_2231485 (2160p).mp4" type="video/mp4">
> indententation should be with 2 spaces

I used vs code extension prettier for indentation and it indented it this way.

2023-07-19 05:42 UTC, mayanktyagi45 commented on embedded.html
> +                    <source src="./assets/pexels_videos_2231485 (2160p).mp4" type="video/mp4">
> indententation should be with 2 spaces

@PurnimaCompro I have made the suggested changes

2023-07-21 04:27 UTC, mayankcompro commented
1. Understand branch naming convention. This naming convention not correct. 
2. Also go through some best practices regarding the commit message as well. For instance, we follow the commit guidelines as follows - 
  `feature-name: Add/Update/Implement/Rename/Delete/etc and then the details `
  
I hope this is clear if not we can meet and discuss.

2023-07-21 04:34 UTC, mayankcompro commented
Also, attach the screenshot of the UI that is designed by this HTML code in the PR description. So that the reviewer should get the proper understanding of the code.

2023-07-21 04:39 UTC, mayankcompro commented on index.html
> +          <label class="label" for="lang">Language</label>
Let's avoid using class name like `label` when we know that it is already applied on label tag. There are other instances as well like in input tag you are using the class as input. It should explain what this input is all about.

Improve all instances in this PR.

2023-07-21 10:40 UTC, mayankcompro approved these changes

2023-07-21 10:42 UTC, merged